"""Method that generates an order id and is called by the views which handle adding to cart."""
import random
import string
import datetime
from datetime import date

def generate_order_id():
    """Returns the order id which is generated by the current date and a random string."""
    date_str = date.today().strftime('%Y%m%d')[2:]+str(datetime.datetime.now().second)
    rand_str = "".join([random.choice(string.digits) for count in range(3)])
    return date_str+rand_str
