# Generated by Django 2.0.7 on 2019-07-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityKg', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('QuantityPieces', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderNum', models.AutoField(primary_key=True, serialize=False)),
                ('OrderTime', models.DateTimeField()),
                ('DeliveryTime', models.DateTimeField()),
                ('Delivered', models.BooleanField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Country', models.CharField(max_length=30)),
                ('County', models.CharField(max_length=30)),
                ('Region', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('AddressNum', models.CharField(max_length=3)),
                ('Postcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('CardNum', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('CardName', models.CharField(max_length=61)),
                ('SecurityCode', models.CharField(max_length=3)),
                ('ExpiryYear', models.PositiveIntegerField()),
                ('ExpiryMonth', models.PositiveIntegerField()),
                ('ReceiptNum', models.AutoField(primary_key=True, serialize=False)),
                ('COD', models.BooleanField()),
                ('OrderNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Barcode', models.CharField(max_length=12)),
                ('Category', models.CharField(max_length=30)),
                ('Subcategory', models.CharField(max_length=30)),
                ('SubCategory2', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Photo', models.ImageField(upload_to='images/')),
                ('Quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('Availability', models.BooleanField()),
                ('OnSale', models.BooleanField()),
                ('SalePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('SaleId', models.AutoField(primary_key=True, serialize=False)),
                ('SalePercent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('TimeStart', models.DateTimeField()),
                ('TimeEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomersWithAccount',
            fields=[
                ('customers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Customers')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Country', models.CharField(choices=[('Ελλάδα', 'Ελλάδα')], max_length=6)),
                ('County', models.CharField(choices=[('Νομός Φωκίδας', 'Νομός Φωκίδας'), ('Νομός Αιτωλοακαρνανίας', 'Νομός Αιτωλοακαρνανίας'), ('Νομός Αργολίδας', 'Νομός Αργολίδας'), ('Νομός Αρκαδίας', 'Νομός Αρκαδίας'), ('Νομός Άρτας', 'Νομός Άρτας'), ('Νομός Αχαίας', 'Νομός Αχαίας'), ('Νομός Αττικής', 'Νομός Αττικής'), ('Νομός Βοιωτίας', 'Νομός Βοιωτίας'), ('Νομός Γρεβενών', 'Νομός Γρεβενών'), ('Νομός Δράμας', 'Νομός Δράμας'), ('Νομός Δωδεκανήσου', 'Νομός Δωδεκανήσου'), ('Νομός Έβρου', 'Νομός Έβρου'), ('Νομός Ευβοίας', 'Νομός Ευβοίας'), ('Νομός Ευρυτανίας', 'Νομός Ευρυτανίας'), ('Νομός Ζακύνθου', 'Νομός Ζακύνθου'), ('Νομός Ηλείας', 'Νομός Ηλείας'), ('Νομός Ημαθίας', 'Νομός Ημαθίας'), ('Νομός Ηρακλείου', 'Νομός Ηρακλείου'), ('Νομός Θεσπρωτίας', 'Νομός Θεσπρωτίας'), ('Νομός Θεσσαλονίκης', 'Νομός Θεσσαλονίκης'), ('Νομός Ιωαννίνων', 'Νομός Ιωαννίνων'), ('Νομός Καβάλας', 'Νομός Καβάλας'), ('Νομός Καρδίτσας', 'Νομός Καρδίτσας'), ('Νομός Καστοριάς', 'Νομός Καστοριάς'), ('Νομός Κέρκυρας', 'Νομός Κέρκυρας'), ('Νομός Κεφαλλονιάς', 'Νομός Κεφαλλονιάς'), ('Νομός Κιλκίς', 'Νομός Κιλκίς'), ('Νομός Κοζάνης', 'Νομός Κοζάνης'), ('Νομός Κορινθίας', 'Νομός Κορινθίας'), ('Νομός Κυκλάδων', 'Νομός Κυκλάδων'), ('Νομός Λακωνίας', 'Νομός Λακωνίας'), ('Νομός Λάρισας', 'Νομός Λάρισας'), ('Νομός Λασιθίου', 'Νομός Λασιθίου'), ('Νομός Λέσβου', 'Νομός Λέσβου'), ('Νομός Λευκάδας', 'Νομός Λευκάδας'), ('Νομός Μαγνησίας', 'Νομός Μαγνησίας'), ('Νομός Μεσσηνίας', 'Νομός Μεσσηνίας'), ('Νομός Ξάνθης', 'Νομός Ξάνθης'), ('Νομός Πέλλας', 'Νομός Πέλλας'), ('Νομός Πιερίας', 'Νομός Πιερίας'), ('Νομός Πρέβεζας', 'Νομός Πρέβεζας'), ('Νομός Ρεθύμνου', 'Νομός Ρεθύμνου'), ('Νομός Ροδόπης', 'Νομός Ροδόπης'), ('Νομός Σάμου', 'Νομός Σάμου'), ('Νομός Σερρών', 'Νομός Σερρών'), ('Νομός Τρικάλων', 'Νομός Τρικάλων'), ('Νομός Φθιώτιδας', 'Νομός Φθιώτιδας'), ('Νομός Φλώρινας', 'Νομός Φλώρινας'), ('Νομός Φωκίδας', 'Νομός Φωκίδας'), ('Νομός Χαλκιδικής', 'Νομός Χαλκιδικής'), ('Νομός Χανίων', 'Νομός Χανίων'), ('Νομός Χίου', 'Νομός Χίου')], max_length=30)),
                ('Region', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('AddressNum', models.CharField(max_length=3)),
                ('Postcode', models.CharField(max_length=5)),
            ],
            bases=('shop.customers',),
        ),
        migrations.CreateModel(
            name='CustomersWithoutAccount',
            fields=[
                ('customers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Customers')),
            ],
            bases=('shop.customers',),
        ),
        migrations.AddField(
            model_name='products',
            name='SaleId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Sales'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customers'),
        ),
        migrations.AddField(
            model_name='contains',
            name='Barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Products'),
        ),
        migrations.AddField(
            model_name='contains',
            name='OrderNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Orders'),
        ),
    ]
