# Generated by Django 2.0.7 on 2019-07-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customerswithaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Surname',
        ),
        migrations.RemoveField(
            model_name='customerswithaccount',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='customerswithaccount',
            name='Username',
        ),
    ]
