# Generated by Django 2.0.7 on 2019-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190722_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Barcode',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(choices=[('Μανάβικο', 'Μανάβικο'), ('Κρεοπωλείο', 'Κρεοπωλείο'), ('Γαλακτοκομικά-Είδη Ψυγείου', 'Γαλακτοκομικά-Είδη Ψυγείου')], max_length=30),
        ),
    ]
