# Generated by Django 2.0.7 on 2019-07-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190722_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(choices=[('Μανάβικο', 'Μανάβικο'), ('Κρεοπωλείο', 'Κρεοπωλείο'), ('Γαλακτοκομικά-Είδη Ψυγείου', 'Γαλακτοκομικά-Είδη Ψυγείου')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubNameSecond', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='SubCategory2',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='shop.SubcategorySecond'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Subcategory',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Subcategory2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SubcategorySecond'),
        ),
        migrations.AddField(
            model_name='category',
            name='Subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
        ),
    ]
