# Generated by Django 2.0.7 on 2019-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190723_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='SubName',
            field=models.CharField(choices=[('Φρούτα', 'Φρούτα'), ('Λαχανικά', 'Λαχανικά')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategorysecond',
            name='SubNameSecond',
            field=models.CharField(choices=[('Μήλα', 'Μήλα'), ('Μπανάνες', 'Μπανάνες')], max_length=255, unique=True),
        ),
    ]
