# Generated by Django 2.0.7 on 2019-07-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190723_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Subcategory',
            new_name='SubcategoryName',
        ),
    ]
