# Generated by Django 2.0.7 on 2019-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190723_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorysecond',
            name='SubNameSecond',
            field=models.CharField(choices=[('Ελλάδα', 'Ελλάδα')], max_length=255, unique=True),
        ),
    ]
