# Generated by Django 2.0.7 on 2019-07-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190723_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Subcategory2',
            field=models.ForeignKey(choices=[('Φρούτα', 'Φρούτα'), ('Λαχανικά', 'Λαχανικά'), ('Γάλα', 'Γάλα'), ('Γιαούρτια', 'Γιαούρτια'), ('Βούτυρο-Μαργαρίνη', 'Βούτυρο-Μαργαρίνη'), ('Κρέμες Γάλακτος-Σαντιγί', 'Κρέμες Γάλακτος-Σαντιγί')], on_delete=django.db.models.deletion.CASCADE, to='shop.SubcategorySecond'),
        ),
        migrations.AlterField(
            model_name='subcategorysecond',
            name='SubNameSecond',
            field=models.CharField(choices=[('Μήλα', 'Μήλα'), ('Μπανάνες', 'Μπανάνες'), ('Χόρτα', 'Χόρτα'), ('Μοσχάρι', 'Μοσχάρι'), ('Χοιρινό', 'Χοιρινό'), ('Φρέσκο Γάλα', 'Φρέσκο Γάλα'), ('Ρόφημα', 'Ρόφημα')], max_length=255, unique=True),
        ),
    ]
