# Generated by Django 2.0.7 on 2019-07-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190723_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CatName',
            field=models.CharField(choices=[('Μανάβικο', 'Μανάβικο'), ('Κρεοπωλείο', 'Κρεοπωλείο'), ('Γαλακτοκομικά-Είδη Ψυγείου', 'Γαλακτοκομικά-Είδη Ψυγείου'), ('Τυροκομικά', 'Τυροκομικά'), ('Αλλαντικά', 'Αλλαντικά'), ('Κατεψυγμένα', 'Κατεψυγμένα')], max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='SubcategoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='SubName',
            field=models.CharField(choices=[('Φρούτα', 'Φρούτα'), ('Λαχανικά', 'Λαχανικά'), ('Γάλα', 'Γάλα'), ('Γιαούρτια', 'Γιαούρτια'), ('Βούτυρο-Μαργαρίνη', 'Βούτυρο-Μαργαρίνη'), ('Κρέμες Γάλακτος-Σαντιγί', 'Κρέμες Γάλακτος-Σαντιγί')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Subcategory2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SubcategorySecond'),
        ),
    ]
