# Generated by Django 2.0.7 on 2019-07-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190723_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='SubName',
            field=models.CharField(choices=[('Φρούτα', 'Φρούτα'), ('Λαχανικά', 'Λαχανικά'), ('Γάλα', 'Γάλα'), ('Γιαούρτια', 'Γιαούρτια'), ('Βούτυρο-Μαργαρίνη', 'Βούτυρο-Μαργαρίνη'), ('Κρέμες Γάλακτος-Σαντιγί', 'Κρέμες Γάλακτος-Σαντιγί')], max_length=255),
        ),
    ]
