# Generated by Django 2.0.7 on 2019-07-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190724_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName2', models.CharField(max_length=255)),
                ('SubName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='SubCategory2',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory2'),
        ),
    ]
