# Generated by Django 2.0.7 on 2019-07-24 17:31

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20190724_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
        ),
    ]
