# Generated by Django 2.0.7 on 2019-07-24 17:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20190724_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Category', chained_model_field='Category', default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
            preserve_default=False,
        ),
    ]
