# Generated by Django 2.0.7 on 2019-07-24 17:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20190724_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Category', chained_model_field='Category', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='shop.Subcategory'),
        ),
    ]
