# Generated by Django 2.0.7 on 2019-07-24 18:01

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20190724_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='products',
            name='Subcategory',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Category', chained_model_field='SubName', horizontal=True, to='shop.Subcategory'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='CatName',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='CatName',
            field=models.ManyToManyField(null=True, to='shop.Category'),
        ),
    ]
