# Generated by Django 2.0.7 on 2019-07-24 18:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190724_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='products',
            name='Subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Category', chained_model_field='Category', default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Subcategory'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='CatName',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='CatName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
