# Generated by Django 2.0.7 on 2019-07-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20190724_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory2',
            name='SubName',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Subcategory2',
        ),
        migrations.DeleteModel(
            name='Subcategory2',
        ),
    ]
