# Generated by Django 2.0.7 on 2019-07-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20190724_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CatName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubName',
            new_name='name',
        ),
    ]
