# Generated by Django 2.0.7 on 2019-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20190724_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Μανάβικο', 'Μανάβικο'), ('Κρεοπωλείο', 'Κρεοπωλείο'), ('Γαλακτοκομικά-Είδη Ψυγείου', 'Γαλακτοκομικά-Είδη Ψυγείου'), ('Τυροκομικά', 'Τυροκομικά'), ('Αλλαντικά', 'Αλλαντικά'), ('Κατεψυγμένα', 'Κατεψυγμένα')], max_length=255),
        ),
    ]
