# Generated by Django 2.0.7 on 2019-07-24 18:52

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20190724_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='CatName_id', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='shop.Subcategory'),
        ),
    ]
