# Generated by Django 2.0.7 on 2019-07-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20190725_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Subcategory2',
        ),
    ]
