# Generated by Django 2.0.7 on 2019-07-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20190725_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory2',
            old_name='SubName2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory2',
            old_name='SubName',
            new_name='subcategory',
        ),
    ]
