# Generated by Django 2.0.7 on 2019-07-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20190725_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Subcategory2',
            new_name='subcategory2',
        ),
    ]
