# Generated by Django 2.0.7 on 2019-07-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20190726_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Name',
            new_name='name',
        ),
    ]
