# Generated by Django 2.0.7 on 2019-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20190726_1420'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'name')},
        ),
    ]
