# Generated by Django 2.0.7 on 2019-07-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20190726_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Availability',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Barcode',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='OnSale',
            new_name='onSale',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='SaleId',
            new_name='saleId',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='SalePrice',
            new_name='salePrice',
        ),
    ]
