# Generated by Django 2.0.7 on 2019-07-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20190726_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='Νame',
        ),
    ]
