# Generated by Django 2.0.7 on 2019-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_auto_20190726_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
