# Generated by Django 2.0.7 on 2019-07-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20190727_1041'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together={('id', 'slug')},
        ),
    ]
