# Generated by Django 2.0.7 on 2019-07-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20190727_1134'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
