# Generated by Django 2.0.7 on 2019-07-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_auto_20190728_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
