# Generated by Django 2.0.7 on 2019-07-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory2',
            name='slug',
            field=models.SlugField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
