# Generated by Django 2.0.7 on 2019-07-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_auto_20190728_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory2',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
