# Generated by Django 2.0.7 on 2019-07-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_auto_20190728_1227'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together=set(),
        ),
    ]
