# Generated by Django 2.0.7 on 2019-07-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_auto_20190728_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contains',
            old_name='QuantityPieces',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='contains',
            name='QuantityKg',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Email',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='shop.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CustomersWithAccount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
