# Generated by Django 2.0.7 on 2019-07-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_auto_20190728_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('OrderNum', models.AutoField(primary_key=True, serialize=False)),
                ('OrderTime', models.DateTimeField(auto_now_add=True)),
                ('DeliveryTime', models.DateTimeField(null=True)),
                ('Delivered', models.BooleanField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('County', models.CharField(max_length=30, null=True)),
                ('Region', models.CharField(max_length=30, null=True)),
                ('Address', models.CharField(max_length=30, null=True)),
                ('AddressNum', models.CharField(max_length=3, null=True)),
                ('Postcode', models.CharField(max_length=5, null=True)),
                ('products', models.ManyToManyField(to='shop.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CustomersWithAccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='contains',
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='contains',
            name='OrderNum',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='OrderNum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart'),
        ),
        migrations.DeleteModel(
            name='Contains',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
