# Generated by Django 2.0.7 on 2019-07-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_auto_20190729_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='TotalAmount',
            new_name='total',
        ),
    ]
