# Generated by Django 2.0.7 on 2019-07-29 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0087_auto_20190729_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerswithaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
