# Generated by Django 2.0.7 on 2019-07-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_auto_20190730_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
