# Generated by Django 2.0.7 on 2019-07-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
    ]
