# Generated by Django 2.0.7 on 2019-07-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_quantity_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='AddressNum',
            new_name='addressNum',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='County',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Region',
            new_name='region',
        ),
    ]
