# Generated by Django 2.0.7 on 2019-07-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0097_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='ref_code',
        ),
    ]
