# Generated by Django 2.0.7 on 2019-07-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0099_auto_20190730_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ref_code',
        ),
    ]
