# Generated by Django 2.0.7 on 2019-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0103_auto_20190731_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerswithoutaccount',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
    ]
