# Generated by Django 2.0.7 on 2019-07-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='ref_code',
        ),
    ]
