# Generated by Django 2.0.7 on 2019-07-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_remove_quantity_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='ref_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
