# Generated by Django 2.0.7 on 2019-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0109_quantity_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
