# Generated by Django 2.0.7 on 2019-07-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_auto_20190731_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
