# Generated by Django 2.0.7 on 2019-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_auto_20190731_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
