# Generated by Django 2.0.7 on 2019-07-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0113_auto_20190731_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ref_code',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
