# Generated by Django 2.0.7 on 2019-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0117_quantity_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='SalePercent',
            field=models.PositiveIntegerField(),
        ),
    ]
