# Generated by Django 2.0.7 on 2019-08-03 13:04

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0119_auto_20190803_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='salePrice',
            field=computed_property.fields.ComputedDecimalField(compute_from='get_sale_price', decimal_places=2, default='1', editable=False, max_digits=4),
            preserve_default=False,
        ),
    ]
