# Generated by Django 2.0.7 on 2019-08-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0120_auto_20190803_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='onSale',
            field=models.BooleanField(editable=False),
        ),
    ]
