# Generated by Django 2.0.7 on 2019-08-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0123_auto_20190803_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='salePrice',
        ),
    ]
