# Generated by Django 2.0.7 on 2019-08-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0124_remove_products_saleprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='onSale',
        ),
    ]
