# Generated by Django 2.0.7 on 2019-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0128_auto_20190804_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Αντικαταβολή', 'Αντικαταβολή'), ('Πληρωμή με κάρτα', 'Πληρωμή με κάρτα')], max_length=30)),
            ],
        ),
    ]
