# Generated by Django 2.0.7 on 2019-08-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0129_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PaymentMethod'),
        ),
    ]
