# Generated by Django 2.0.7 on 2019-08-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0132_auto_20190804_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PaymentMethod'),
        ),
    ]
