# Generated by Django 2.0.7 on 2019-08-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0133_auto_20190804_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_added_to_cart',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
