# Generated by Django 2.0.7 on 2019-08-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0135_auto_20190814_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.OrderItem'),
        ),
    ]
